### ISSUE TITLE
UI - Scaling of modals(Like Sign in/up) doesn't scale or show scrollbars

### ISSUE THREAD

**Issue by Drakran** [Touchpoint-edu/TouchPoint#81]

**Comment by ellyrberge** [comment]
<img width="1792" alt="Screen Shot 2021-05-07 at 11 10 34 PM" src="https://user-images.githubusercontent.com/54693674/117524012-89127280-af89-11eb-87c0-d909fb877211.png">

**Comment by ellyrberge** [comment]
![Uploading Screen Shot 2021-05-07 at 11.11.50 PM.png…]()

**Comment by ellyrberge** [comment]
Resolve
